### ISSUE TITLE
[아이템 1] 다섯 번째 장점에 대한 쉬운 설명과 예시가 필요해요.

### ISSUE THREAD

**Issue by JinseongHwang** [Reading-Effective-Java/community#1]
## 내용

<div align=center><i><b>
다섯 번째, 정적 팩터리 메서드를 작성하는 시점에는 반환할 객체의 클래스가 존재하지 않아도 된다.
</b></i></div><br>

자바 봄 그룹에서도 비슷한 [이슈](https://github.com/Java-Bom/ReadingRecord/issues/3)가 있어서 찾아봤는데, [예제 코드](https://github.com/Java-Bom/ReadingRecord/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%20%EC%9E%90%EB%B0%94/effectiveJava/src/main/java/Chap2_GenerateObjectAndDestroy/item1/jdbc/JdbcSample.java)를 봐도 잘 이해가 안되네요.. 부가적인 설명이 필요합니다.

**Comment by meanjoo** [comment]
찾아봤을 때 여기에서 다섯 번째 장점의 괜찮은 예시를 들고 있는 것 같은데 저는 잘 모르겠어서.. 
[https://debaeloper.tistory.com/20](url)
다섯 번째 장점에 대해서 완벽하게 이해하지는 못했지만 제가 찾아보고 생각한 것을 말해볼게요.

우선 저는 "정적 팩터리 메서드를 작성하는 시점에는 반환할 객체의 클래스가 존재하지 않아도 된다"를 
구현되지 않은 인터페이스라도 정적 팩터리 메서드의 반환값으로 사용되어 객체를 생성할 수 있는 것이라고 이해했습니다.

```
//Main.java
public class Main {
	public static void main(String[] args) {
		List<BookInterface> books = Book.getInstance();
	}
}
```
```
//Book.java
public class Book {
	public static List<BookInterface> getInstance(){
		return new ArrayList<>();
	}
}
```
```
//BookInterface.java
public interface BookInterface {
	
}
```

main에서 books는 정적 팩터리 메서드를 통해서 객체를 얻으려 하고 있습니다. 
정적 팩터리 메서드를 보면 반환값이 인터페이스인데, 
반환값이 인터페이스라는 것은 해당 인터페이스를 구현한 클래스를 반환한다고 합니다.

코드에는 BookInterface를 상속받아 구현한 클래스가 없지만 books는 생성 가능하다는 것이 다섯 번째 장점이 의미하고 있는 바라고 생각합니다.

현재 books는 아무것도 아니지만 이후에 BookInterface를 상속받은 클래스를 구현하고 main에서 생성하여 books에 add하면 books를 사용할 수 있다고 합니다.
인터페이스를 상속받은 클래스를 직접 정의해서 제공할 수 있다는 점에서 유연하다고 하는 것 같아요.
```
//클래스를 구현한 후
public class NewBook implements BookInterface{ .. }

//main의 books를 생성한 코드 뒤에 아래 내용을 추가
BookInterface newBook = new NewBook();
books.add(newBook);
```

 어느 정도까진 이해를 하겠는데 다섯 번째 장점이 명확하게 무엇인지, 이를 어떤 경우에  활용하는 것인지는 잘 모르겠습니다..

조금이라도 도움이 되셨으면 좋겠습니다!

**Comment by JinseongHwang** [comment]
자문자답 용도로 만들었던 이슈였는데 도움 주셔서 감사합니다.

설명해주신 내용을 읽고 다른 코드들을 보니 눈에 들어오네요 ㅋㅋㅋㅋ

이해됐습니다. 감사합니다 :)
