### ISSUE TITLE
[아이템 10] 논리적 동치에 대해서 질문있습니다.

### ISSUE THREAD

**Issue by jhparkland** [Reading-Effective-Java/community#10]
아이템 10 52p 논리적 동치성에 대한 질문입니다

__논리적 동치란__

두 명제 p,q의 쌍방조건 p <-> q가 항진명제이면 두 명제 p,q는 __논리적 동치__ 라고한다 여기서 __항진명제__
란 긱 명제의 참과 거짓의 모든 조합에 대해 항상 참인 것을 말한다.

ex : 명제 p가 "자유가 아니다" 명제 q가 "죽음을 달라" 일때

- 명제 p와 q가 참일 때,
	- ```p -> q``` 는 자유가 아니라면 죽음을 달라 : 참
	- ```p^(p->q)``` 는 자유가 아니다 AND (자유가 아니라면 죽음을 달라) : 참
	- ```(p^(p->q))->q ```는 자유가 아니다 AND (자유가 아니라면 죽음을 달라) 면 죽음을 달라 : 참
- 명제 p가 참이고 명제 q가 거짓일 때,
	- ```p->q``` 는 자유가 아니라면 죽음을 달라 : 거짓
	- ```p^(p->q)``` 는 자유가 아니다 AND (자유가 아니라면 죽음을 달라) : 거짓
	- ```(p^(p->q))->q``` 는 자유가 아니다 AND (자유가 아니라면 죽음을 달라) 면 죽음을 달라 : 참

라고 하는데.. 조금 더 이해 쉽게 설명 가능할까요 ,, 

AND를 뭐라고 해석하는게 좋을까요?
그리고 참 거짓은 무슨 기준으로 판단하나요?

**Comment by choigy1001** [comment]
저희가 다루는 타입으로 한번 생각해봅시다.

* p가 int q가 int라고 정하고, int 는 무조건 참이라고 가정하겠습니다
  - `p->q` p는 q이다 int->int이다. 참이 됩니다.
  - `p^(p->q)`에서  p->q는 참이라 했고 and는 if 조건문을 쓸 때 and를 생각하면 int && int = int이니 참이 되겠죠?
둘다 참일때 예제는 이런식으로 잘 이해가 될거 같습니다..

* 그러면 p가 int이고 q가 char입니다. int가 참이라는 가정은 똑같습니다. char는 반대로 거짓이 됩니다.
  - 이럴때 `p->q` p는 q이다  int 는 char가 되지 못합니다 거짓
  - `p^(p->q)`는  p->q는 이미 앞에서 거짓이라 했고 and연산으로 인해 당연히 거짓이 됩니다.
  - 그렇다면 `(p^(p->q))->q`이다 에서 -> 연산자 앞에 는 거짓이라고 이미 알고 있습니다. 그런데 q또한 거짓입니다 그렇다면 거짓을 char로 뒀던 가정에 의해 char-> char 이다 될겁니다.. 
 
막상 쓰고보니 좀 이상한 비유가 됐지만 이해에 도움이 되셨으면 합니다.

**Comment by jhparkland** [comment]
설명을 보다 보니 논리 게이트 부정이 생각나게 만드는데

이해는 완료했습니다 감사합니다~
