### ISSUE TITLE
[아이템 15] public static final 필드 공개

### ISSUE THREAD

**Issue by choigy1001** [Reading-Effective-Java/community#11]
99p
2번째 문단에 정직 필드에서 예외로
해당 클래스가 표현하는 추상 개념을 완성하는데 꼭 필요한 구성요소로써의
상수라면 `public static final` 필드로 공개해도 좋다.

보통 상수로써 이렇게 사용하는걸 봤는데
```java
public static final int SIZE = 10;
```
여기서 의미하는 추상 개념이 어떤건지 궁금합니다!..

**Comment by kkt219a** [comment]
직접적으로 명시된 자료가 없어 생각을 기반으로 말할게요.
추상 개념의 일반적인 뜻은 말 그대로 막연한 개념, 클래스 자체는 객체를 생성하기 위한 일종의 틀이죠.

그래서 클래스가 표현하는 추상개념을 완성하는데 꼭 필요한 구성요소라는 것은, 
클래스가 자신의 역할에 대해서 필드와 메소드로 정의를 할 것이고, javadoc을 통해서 사용자가 이해할 수도 있지만
단순히 필드와 메소드들로 직관적으로 이해할 수 있도록 정의하는 과정을 설명하는 것으로 이해했어요.

실제 자바 라이브러리에서 사용하고 있는 public static final 필드들을 찾아보면,

```java
// Boolean Class -> TYPE을 호출하면 Boolean 클래스가 Primitive type으로 boolean을 사용하고 있다고 반환한다.
public static final Boolean TRUE = new Boolean(true);
public static final Boolean FALSE = new Boolean(false);
public static final Class<Boolean> TYPE = (Class<Boolean>) Class.getPrimitiveClass("boolean");

// Math Class
public static final double E = 2.7182818284590452354;
public static final double PI = 3.14159265358979323846;

// Integer Class
public static final int   MIN_VALUE = 0x80000000;
public static final int   MAX_VALUE = 0x7fffffff;
public static final Class<Integer>  TYPE = (Class<Integer>) Class.getPrimitiveClass("int");

//Thread Class
public static final int MIN_PRIORITY = 1;
public static final int NORM_PRIORITY = 5;
public static final int MAX_PRIORITY = 10;
```

위 코드들의 예시를 봤을 때,
 Integer 클래스를 사용하면서 최대 최소값을 지정해야한다거나, javadoc을 보면서 할 수도 있지만
`Integer.(MIN or MAX)_VALUE`를 사용하면 클라이언트의 입장에서는 따로 상수를 걸 필요도 없고
Integer 클래스 자신의 상태를 표현하는, 자신의 추상적인 개념을 표현하기 위해 필요한 구성요소라고 볼 수 잇겠죠.

Math 클래스를 사용하며 다양한 공식들을 사용할거고, 내부의 E와 PI는 이 객체가 수학적인 것을 활용하는 클래스라는 것을
더 확실하게 명시가 가능할 것이고, 쓰레드 클래스에서는 사용자가 사용할 때 우선순위에 대해서 설정을 할 때 벗어나지 않게
가이드 역할을 해주는 것이죠

물론 private static final을 사용하여 메소드로 가져올 수도 있겠지만, 상수로 나타내는 것이 더 직관적이게 가져올 수 있고
API에 명백하게 드러나며 간결한 방법이죠. 이는 아이템 3에서 public static final 필드 방식의 싱글톤의 장점이었고,
싱글톤을 이러한 방식으로 쓰지않게 변화한건 리플렉션 방어, 나아가 멀티쓰레드에서의 위험에서 벗어나기위해 계속 수정된 예시이고

책에 나와있듯 불변 객체나 기본타입의 경우에는 이러한 단점도 없고 오히려 더 직관적으로 클래스의 추상개념을
완성한다 즉, 클래스 본인의 역할에 대해서 코드레벨에서 알려줄 수 있다는 점이 추상적인 개념을 완성하는데 꼭 필요한 요소라고
생각합니다. 이와 다른 견해가 있으신 분 있으면 다양한 경우와 의견을 나눠보면 좋을 것 같아요.

**Comment by kkt219a** [comment]
추가로 제가 진행중인 프로젝트에서 public static final을 활용하는 경우는 아래와 같아요
해당 클래스가 가진 추상적인 개념을 더 명확하게 이해하기 위해서도 있고, 인스턴스 없이 자주 등장하는 내용들을 넣었고,
 이 url로 어떤 결과들이 나올 수 있는지 직관적으로 나타내기 위해 주소를 직접 넣은 경우죠
유사하게 만들었었다고 생각은 하는데 완전히 일치하는진 모르겠어요

클래스의 역할은 DB에 저장된 파일정보를 객체로 가져와 파일 스토리지에 저장된 url 주소로 변환하는 역할입니다. 
```java 
public class ImageUrl {
    private final String url;
    private static final String STORAGE_URL = S3.URL; // 또 다른 클래스에 정의된 기본 파일 스토리지 url을 가져옴
    public static final String DEFAULT_LOGO = STORAGE_URL+"/default_logo.png";
    .... 
    // 이 외 다양하게 많이 사용되는 url 들이 public static final로 선언됨 
    ....
    public ImageUrl(s3Image image){
        // 대충 파일을 url로 변환하는 과정, 이 과정에서 다양한 validation을 진행함 이미지가 맞는지나 그런 것
        ....
    }
}
```

**Comment by choigy1001** [comment]
소중한 답변 감사합니다.
쭉 읽어봤는데 저도 똑같이 생각이 드는게 필드나 메소드를 통해 클래스의 추상개념을 완성시키면 그 필드나 메소드를 통해 무슨 클래스인지 파악할 때 더 직관적으로 볼 수 있겠네요.

작성해주신 답변에 싱글턴이나 리플렉션 관련해서 다시 보게 되었습니다.
예시까지 들어주셔서 보여주시니 조금 더 어떻게 사용해야 할지 알게 되었습니다! :joy:
