### ISSUE TITLE
[아이템 34] toString 재정의를 통한 출력

### ISSUE THREAD

**Issue by choigy1001** [Reading-Effective-Java/community#12]
215p의 코드들에 대한 질문입니다!
여기서 메인 메서드를 보면 `op`의 출력이 `toString`의 재정의 유무에 따라 바뀌게 되는데
무엇 때문에 이렇게 바뀌게 되는지 궁금합니다.

ex)
책 예제대로 toString 재정의 시
`3.000000 + 4.000000 = 7.000000`

재정의 안할 시
`3.000000 PLUS 4.000000 = 7.000000`

마지막 문단에 열거 타입에는 상수 이름을 입력받아 그 이름에 해당하는 상수를 반환해주는 valueOf(String) 메서드가 자동 생성된다.
이 문장이랑 관련이 있는건가요?

**Comment by kkt219a** [comment]
책에서 나온 소스 그대로 설명할게. 우선 enum인 Operation에 다른 필드가 없다고 가정해보자.
```
public enum Operation { PLUS, MINUS, TIMES, DIVIDE; }
```

이 때 enum 추상클래스가 어떻게 구성되는지를 확인해보면 아래와 같아. 
```
public abstract class Enum<E extends Enum<E>> implements Comparable<E>, Serializable {
    private final String name;
    public final String name() { return name; }
    private final int ordinal;
    public final int ordinal() { return ordinal; }
    ...
}
```

간단하게 내부구성을 살펴보면 name 필드는 열거상수의 이름, 즉 Operation에서 선언한 PLUS ... DIVIDE가 되고,
ordinal 필드는 상수고, 생성자는 있지만 우리가 지정할 수 없고, EnumSet이나 EnumMap에서 활용하기위해 0부터 초기화 돼.
따라서 우리가 나열한 열거상수의 순서대로 0,1,2,3이 채워져 있고. 그리고 name() 메소드는 name 필드를 반환하고
이 Enum 추상클래스의 toString도 name필드를 반환해. docs 내용대로면 toString이 더 친근하기 때문에 이 사용을 권하는 것도 알 수 있고.

즉, 우리가 Enum을 사용하면서 toString을 재정의하지 않는이상, 열거상수의 이름인 name필드가 반환되서 PLUS...DIVIDE가 반환되는거야.
현재 책의 소스대로 symbol이라는 String필드를 선언했고, 이 필드에 각 +, -, *, / 문자열을 넣었지. 가능한 이유는 물론 Operation 생성자를
만들어줬기 떄문이고. 이렇게 필드를 추가했어도 toString은 열거상수의 이름을 반환하기 때문에 재정의를 통해 symbol을 반환하게 하는거야.

valueOf 메소드는 enum에서 static 메소드로 제공하고 구현체에서 사용할 때는 클래스타입을 생략하고 상수의 이름만 매개변수로
넘기면 해당하는 상수를 반환하는거라 위에 질문했던 내용과는 무관하다고 생각해

**Comment by choigy1001** [comment]
저도 더 알아보니 valueOf 메서드는 제가 궁금한거랑 관련이 없는거 같아요.
여러가지 몇개 만져보니 소스 코드에 있는 그냥 PLUS만 출력해도 그냥 심볼값이 출력되더라구요.
이게 생성자와 toString 재정의 때문인 거 같은데 일단 어떤 의미로 사용되는지 알게 됐습니다!
