### ISSUE TITLE
[아이템 39] 클래스 파일이 컴파일타임에 존재했으나 런타임에 존재하지 않는 경우

### ISSUE THREAD

**Issue by kkt219a** [Reading-Effective-Java/community#14]
p.242의 2문단 마지막 줄에 클래스 파일이 컴파일 타임에 존재했으나 런타임에 존재하지 않는 경우에
TypeNotPresentException이 발생한다는데, 저 예외가 뭔지는 알겠는데 저런 경우에 대한 예시 궁금!

**Comment by choigy1001** [comment]
제가 찾아서 이해한 내용은 
TypeNotPresentException이 사용하려는 타입이 정의되어 있지 않아서 발생하는 예외라고 이해했어요. 
하지만 보통 저희가 사용할 때 사용하려는 타입이 없는 경우에는 컴파일 타임에서 다 거르는데 만약 컴파일에는 존재하나 런타임에 존재하지 않는 경우는 java와 javac의 클래스 경로가 다른 경우가 아닌가 싶네요.

https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=down83&logNo=50086938341
여기 블로그에서는 class 파일이 제대로 수정되지 않아 예외가 발생한 거 같아요. 추측밖에 없는 답변이라 좀 슬프네요. 
이전 이슈 포함해서 저도 궁금했던 내용이라 계속 찾아보고 답변 달아볼게요.

**Comment by kkt219a** [comment]
컴파일 후, 쓰레드에 20초 지연을 준 상태에서 컴파일된 Exception.class을 삭제함
--> TypeNotPresentException

실무에서는 이런 일이 발생하지 않을 것 같은데, 다른 이유로 컴파일된 파일중 일부가 손실될 수 있는지는 모르겠음 😭
