### ISSUE TITLE
[아이템 59] Random 클래스의 nextInt()와 URL 예제

### ISSUE THREAD

**Issue by kkt219a** [Reading-Effective-Java/community#15]
p351. 앞의 두가지 문제점에서
n이 크지않은 2의 제곱수와 2의 제곱수가 아닐때 평균적으로 더 자주 반환된다고 나와있는데
n을 Integer.MAX_VALUE로 설정하거나 /2, /3을 했을 때는 중간값에 거의 수렴하던데 왜 그런건지 궁금해요
+
p352. nextInt(int)의 돌아가는 구조 파라미터가 없는 경우와 어떤 차이가 있는건지 간단하게 설명이 있으면 좋을 거 같아요
p353. transferTo와 URL을 이용하는 코드가 어떤 동작을 하는건지 궁금해요

**Comment by meanjoo** [comment]
책에서 random 메서드의 인자인 n이 2의 제곱수가 아니라면 몇몇 숫자가 더 자주 반환되어 값이 한 쪽으로 쏠린다고 하는데, 우선 저는 한 쪽으로 쏠린다는 걸 n이 2의 제곱수냐 아니냐가 아닌 다른 방식으로 이해했어요. 

질문에 대한 답을 제가 이해한 방식을 바탕으로 그린 그림을 통해 설명해볼게요. (혹시 그림이 보이지 않으면 말해주세요)

그 전에 먼저 코드 59-1의 random 메서드는 Random 클래스의 nextInt()를 사용해서 무작위 정수를 하나 생성한 후 정수 범위를 0부터 n 미만으로 제한하여 반환합니다. 
Random 클래스의 nextInt()는 int형 표현 범위 숫자 중 하나를 반환하는데, 명세 중 
>All 2<sup>32</sup> possible int values are produced with (approximately) equal probability. 

이라는 문장이 있습니다. nextInt()가 반환할 수 있는 값은 모두 거의 동일한 확률로 생성된다고 해요.
![351](https://user-images.githubusercontent.com/88606886/143674234-2bfcd46b-c437-4ca3-89d3-37059c5704b2.jpg)
그림에서 ①~④ 각각의 막대는 Math.abs(rnd.nextInt())가 반환하는 값의 범위(352p에서 설명하는 세 번째 결함은 설명에 크게 영향을 주지 않아서 일단 고려하지 않았습니다..!)이고, 
빨간색 빗금 표시 부분은 random 메서드가 반환하는 값의 범위(그림의 a, b 영역)입니다.

①인 경우 random 메서드에서 Math.abs(rnd.nextInt())가 c 영역의 값을 반환하면 % 연산에 의해서 random 메서드는 a 영역의 값을 반환합니다.
위에서 nextInt()의 반환 값은 거의 동일한 확률로 생성된다고 했으므로, 
100만 개의 무작위 정수를 생성했다면 Math.abs(rnd.nextInt())는 a, b, c 각각의 영역에서 약 333,333개씩의 무작위 정수를 생성할 것입니다. 
그런데 random 메서드는 c 영역의 값을 a 영역의 값으로 매핑시켜 반환하기 때문에, random 메서드가 100만 번 수행되면 a 영역의 값을 약 666,666개, b 영역의 값을 약 333,333개 반환할 것입니다. 
n/2 미만인 값의 개수를 세는 low는 a 영역에서 생성된 값의 개수이므로 약 666,666에 가까운 값을 가지게 됩니다.

②인 경우에는 n으로 제한한 범위와 Math.abs(rnd.nextInt())가 반환하는 값의 범위가 같기 때문에 % 연산은 큰 의미가 없고, random 메서드는 Math.abs(rnd.nextInt())를 그대로 반환합니다. 
random 메서드가 100만 번 수행되면 a, b 각각의 영역에 속하는 값을 약 500,000개씩 반환할 것입니다. 
n/2 미만인 값의 개수를 세는 low는 a 영역에서 생성된 값의 개수이므로 약 500,000에 가까운 값을 가지게 됩니다.

③인 경우에는 100만 개의 무작위 정수를 생성하면 Math.abs(rnd.nextInt())는 a, b, c, d 각각의 영역에서 약 250,000개씩의 무작위 정수를 생성할 것입니다. 
random 메서드는 c 영역의 값을 a 영역의 값으로, d 영역의 값을 b 영역의 값으로 매핑시켜 반환합니다. 
random 메서드가 100만 번 수행되면 a 영역의 값을 약 500,000개, b 영역의 값을 약 500,000개 반환합니다. 
n/2 미만인 값의 개수를 세는 low는 a 영역에서 생성된 값의 개수이므로 약 500,000에 가까운 값을 가지게 됩니다.

마찬가지로 ④인 경우도 100만 개의 무작위 정수를 생성하면 Math.abs(rnd.nextInt())는 a, b, c, d, e, f 각각의 영역에서 약 166,667개씩의 무작위 정수를 생성할 것입니다. 
random 메서드는 c, e 영역의 값을 a 영역의 값으로, d, f 영역의 값을 b 영역의 값으로 매핑시켜 반환합니다. 
random 메서드가 100만 번 수행되면 a, b 영역의 값을 각각 약 500,000개 반환합니다. 
n/2 미만인 값의 개수를 세는 low는 a 영역에서 생성된 값의 개수이므로 약 500,000에 가까운 값을 가지게 됩니다.

이게 제가 이해한 방식인데, 왜 책에서 n이 2의 제곱수가 아닐 때 몇몇 숫자가 평균적으로 더 자주 반환된다고 설명하는지는 저도 궁금하네요. n이 2의 제곱수인 것과 아닌 게 무슨 의미가 있는지 찾아보다가 답이 늦어졌는데 여전히 잘 모르겠어요 ...

\-

nextInt(int)의 돌아가는 구조 파라미터가 없는 경우와의 차이라는 게 nextInt()와 nextInt(int)의 차이를 물으시는 건가요?
이런 질문이라고 생각하고 답을 하는데 혹시 질문의 의도가 이게 아니었다면 다시 말해주세요!

0부터 n 미만의 무작위 정수를 하나 생성하고 싶은데 Random.nextInt() 메서드만 아는 경우에는 코드 59-1처럼 메서드를 직접 만들어야 합니다. 
하지만 책에서도 말하듯 이렇게 만든 메서드에는 문제점들이 있습니다. 
이 문제점들을 해결하여 전문가들이 만들어놓은 메서드가 Random.nextInt(int)입니다.

Random.nextInt() 메서드는 아래와 같이 정의되어 있습니다.
```
public int nextInt() {
    return next(32);
}

protected int next(int bits) {
    long oldseed, nextseed;
    AtomicLong seed = this.seed;
    do {
        oldseed = seed.get();
        nextseed = (oldseed * multiplier + addend) & mask;
    } while (!seed.compareAndSet(oldseed, nextseed));
    return (int)(nextseed >>> (48 - bits));
}
```
Random.nextInt(int) 메서드는 아래와 같이 정의되어 있습니다. 
```
public int nextInt(int bound) {
    if (bound <= 0)
        throw new IllegalArgumentException(BadBound);

    int r = next(31);
    int m = bound - 1;
    if ((bound & m) == 0)  // i.e., bound is a power of 2
        r = (int)((bound * (long)r) >> 31);
    else {
        for (int u = r;
            u - (r = u % bound) + m < 0;
            u = next(31))
           ;
    }
    return r;
}
```
코드를 봐도 수학적인 내용 같아서 어떤 원리로 nextInt(int bound)가 random(int n)의 문제점을 해결하는지는 잘 모르겠어요.
제가 코드를 보고 알 수 있는 점은 random(int)에서 쓴 Random.nextInt()는 n이 2의 제곱수일 때와 2의 제곱수가 아닐 때를 구분하지 않고 난수 생성을 위해 next(32)를 사용하며,
Random.nextInt(int bound)는 bound가 2의 제곱수일 때와 2의 제곱수가 아닐 때를 구분하고 난수 생성을 위해 next(31)을 사용하는 점 정도인 것 같아요.

Random.nextInt(int)의 명세 중 아래와 같은 말이 있습니다.
>The algorithm treats the case where n is a power of two specially: it returns the correct number of high-order bits from the underlying pseudo-random number generator. In the absence of special treatment, the correct number of low-order bits would be returned. Linear congruential pseudo-random number generators such as the one implemented by this class are known to have short periods in the sequence of values of their low-order bits. Thus, this special case greatly increases the length of the sequence of values returned by successive calls to this method if n is a small power of two.

이 알고리즘은 bound가 2의 제곱수일 때를 특별하게 처리하는데, 그 이유가 Random 클래스에서 사용하는 난수 생성기 자체가 bound가 그리 크지 않은 2의 제곱수라면 얼마 지나지 않아 같은 수열이 반복된다고 합니다. (351p에서 말하는 random 메서드의 첫 번째 문제점) 
이를 해결하기 위해 bound가 그리 크지 않은 2의 제곱수일 때 값의 시퀀스 길이를 늘린다고 해요. 
그 방법이 아마 반환 값인 ```r```을 ```r = (int)((bound * (long)r) >> 31);``` 로 해주는 게 아닐까 생각해요.
나머지 코드는 읽어봐도 어떻게 저런 코드를 짜게 된 건지는 잘 모르겠어요.

\-

InputStream의 transferTo 메서드는 입력 스트림으로부터 모든 바이트를 읽고, 읽은 순서대로 지정된 출력 스트림에 바이트를 쓴다고 해요.
353p의 코드 59-2는 명령줄에 URL을 주면 그 URL의 내용을 화면에 출력해주는 코드인 것 같아요.
예를 들어 명령줄에 "https://www.google.co.kr" 를 입력하면 https://www.google.co.kr 의 내용(페이지 소스 보기)이 화면에 출력됩니다.

```
public static void main(String[] args) throws IOException {
    System.out.print("URL→ ");
    Scanner sc = new Scanner(System.in);
    String url = sc.nextLine();


    FileOutputStream fos = new FileOutputStream("C:/Users/user/Desktop/urlTest.txt");
    try(InputStream in = new URL(url).openStream()) {
        in.transferTo(fos);
    }
    fos.close();
}
```
위 코드처럼 URL을 입력 받아서 화면에 출력하지 않고 경로를 지정하여 원하는 곳에  URL의 내용을 파일로도 저장할 수도 있는데, 
이렇게 URL의 내용을 파일에 가져온 후에 어디에 활용을 할 수 있는지는 잘 모르겠어요.

아니면 아래처럼 존재하는 파일의 내용을 다른 파일에 복사하는 용도로도 활용할 수 있을 것 같아요.
```
public static void main(String[] args) throws IOException {
    FileOutputStream fos1 = new FileOutputStream("C:/Users/user/Desktop/input_copy.txt");
    try(InputStream in = new FileInputStream("C:/Users/user/Desktop/input.txt")) {
        in.transferTo(fos1);
    }
    fos1.close();
}
```
모르는 부분이 더 많은 거 같은데 조금이라도 궁금증이 해결되셨으면 좋겠습니다!..

**Comment by kkt219a** [comment]
설명해주셔서 감사합니다~

말씀 하신 내용대로 좀 더 살펴봤고, 첫 번째 문제에 대해서는 다음과 같이 정의할 수 있을 것 같아요.
세번째 문제는 번외로 두고 0을 포함한 양수를 반환한다고 했을 때
수의 범위가 0~7(2^3 -1)일 때, 2의 n 제곱수 2와 4로 나눈 나머지는 (0,1,0,1,0,1,0,1)과 (0,1,2,3,0,1,2,3)으로 맞아 떨어지게 되더라고요.
2의 제곱수가 아닌 3과 5로 나눠보면 (0,1,2,0,1,2,0,1), (0,1,2,3,4,0,1,2)과 같이 맞게 떨어지지 않고 몇몇 숫자는 잦은 빈도를 가지고요.

0~2^32- 1까지, 일반화를 해보면 2의 n 제곱수들은 빈도가 모두 같음은 물론, 같은 시퀀스 반복된다는 것을 알 수 있어요.
책에서 2의 n 제곱수가 아닌 제곱수라고 나와있는게 의문이었는데 비슷한 이슈가 보여서 첨부했고, 2의 제곱수가 아닌 n 제곱수가 맞는 것 같아요.
https://stackoverflow.com/questions/27779177/effective-java-item-47-know-and-use-your-libraries-flawed-random-integer-meth/27779402#27779402

그리고 선형합동생성기의 특성을 보면 2의 거듭제곱이 하위비트에서 같은 시퀀스가 반복되기 때문에 하위 비트를 버리고 상위 비트를 주로 채택한다고 나와있는데, 이는 nextInt(int)의 2 거듭제곱수에서 시프트 연산을 하는 이유가 상위비트를 채택해서 반환하기 위함으로 보이네요.
https://ko.wikipedia.org/wiki/%EC%84%A0%ED%98%95_%ED%95%A9%EB%8F%99_%EC%83%9D%EC%84%B1%EA%B8%B0

n이 2의 거듭제곱수가 아닌경우에 사용하는 공식을 살펴보았을 때, 편향시키는 랜덤 값에 대해서 재계산을 합니다.
```
   int bits, val;
   do {
       bits = next(31);
       val = bits % bound;
   } while (bits - val + (bound-1) < 0);
```

책에서 사용한 예제들의 값을 씌워볼게요
bound: 1431655764( n, 2*(Integer.MAX_VALUE / 3) )
bits = 1500000000 ( bound보다 높은 랜덤 결과값으로, 편향된 값에 속함)
val = 68344236 ( 이때 나머지는 다음과 같음)

그러면 이 공식대로
bits - val + (bound-1) = -1, 즉 편향된 값으로 판단이 되어 재계산해서 양수가 나오면 편향된 값이 아님으로 반환합니다.
이 알고리즘의 최악의 경우는 다음과 같다네요
```
The algorithm is slightly tricky. It rejects values that would result in an uneven distribution (due to the fact that 2^31 is not divisible by n). The probability of a value being rejected depends on n. The worst case is n=2^30+1, for which the probability of a reject is 1/2, and the expected number of iterations before the loop terminates is 2.
```
n이 2^30+1일 경우, 거부될 확률은 1/2! 2^31의 절반인 2^30보다 1큰 경우, 나머지 50%에 가까운 값들은 전부 재계산 되야한다는거죠.
참고할만한 레퍼런스는 아래와 같습니다.
https://stackoverflow.com/questions/66539039/understanding-java-random-next-integer-with-bound-algorithm


두 번째 문제 n값이 2의 제곱수가 아니고 값이 클 때 빈도수 차이가 발생하는 것에 대해서 그려주신 2*(MAX_VALUE/3) 에서 더 잘게 나눴습니다.


![image](https://user-images.githubusercontent.com/30515636/143802239-b5a064cd-fe5c-4df8-8557-cf8f5aaa32cd.png)


MAX_VALUE 범위 내에서 2*(MAX_VALUE/3)일 때 빈도수가 가장 크고 수가 작아질수록 빈도수가 줄어드는 것을 확인했고
특수한 분수형태의 명시한 수를 가질 경우 분포도에 따라서 확률은 제각기 다르게 나타나는 이유를 여기서 확인할 수 있습니다.
