### ISSUE TITLE
[아이템 76] 실패를 가로채는 복구 코드

### ISSUE THREAD

**Issue by choigy1001** [Reading-Effective-Java/community#17]
p408 3번째 문단에 마지막 방법으로 작업 도중 발생하는 실패를 가로채는 복구 코드를 작성하여 작업 전 상태로 되돌리는 방법을 언급했는데 혹시 이 부분에 대해서 어떻게 이해하셨는지 궁금합니다!

###### 중요한 내용은 아닌거 같은데 어떻게들 이해하셨는지 궁금하네요..

**Comment by kkt219a** [comment]
실패를 가로채는 복구 코드를 작성해 작업 전으로 되돌리는 상황은 일반 PC로 보면 어떤 프로그램을 설치하다 오류가 발생하면 설치 이전과 동일하게 되돌려야하고, 데이터베이스라면 다량의 트랜잭션을 수행하다가 오류가 발생했을 때  트랜잭션 이전으로 롤백해야 하는 상황을 생각했어.

https://velog.io/@jinh2352/%EB%94%94%EC%8A%A4%ED%81%AC-%EA%B8%B0%EB%B0%98-%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0-%EC%9D%B4%EC%A7%84-%ED%83%90%EC%83%89-%ED%8A%B8%EB%A6%AC%EC%9D%98-%ED%95%9C%EA%B3%84

위 레퍼런스를 보면 디스크 기반의 내구성을 보장하는 자료구조로 B-tree를 사용한다는 것과 이유가 나와있어.
데이터베이스를 예시로 든 이유는, B-tree는 데이터베이스의 자료구조로까지 이용되기에(B+ tree도 이용되고, 이외에도 디스크 기반이 아닌 인메모리 등 다양한 방법 존재) 이 상황에서 실패할 수 있는 사례를 생각했을 때 트랜잭션이 실패 후 롤백하는 상황이지 않을까? 싶은데 나도 이건 100% 확실하다곤 못하겠어 😭
