### ISSUE TITLE
[아이템 1]  세 번째 장점 하위 타입 객체를 반환함으로써 API 가 작아진다

### ISSUE THREAD

**Issue by choigy1001** [Reading-Effective-Java/community#2]
정적 팩터리 메소드를 사용함으로써 하위 타입 객체를 반환할 수 있다고 했는데, 
구현 클래스를 공개하지 않으면서 하위 타입 객체 반환하면 어떻게 API가 작아진다는 건지 궁금하네요.
밑에 코드는 장점에 해당하는 예시를 찾아봤습니다.. 
```java
public static <T> List<T> asList(T... a) {
    return new ArrayList<>(a);
}
```

**Comment by JinseongHwang** [comment]
우선, 저는 API가 작아진다는 표현을 "구현해야 할 메서드의 개수가 적어진다."라고 이해했습니다.
이는 인터페이스를 정적 팩터리 메서드의 반환 타입으로 두고 있기 때문에 가능하다고 생각해요.

정적 팩터리 메서드의 예시를 가지고 오셨는데, 
`asList()` 메서드는 항상 `ArrayList<>` 라는 구현 클래스를 제공하고 있습니다.
그 말은, 반환 타입을 `ArrayList<>` 타입으로 설정해도 무방하다는 의미겠죠?
이유를 추측해보자면, 추후 확장 가능성을 열어두려고 `List<>` 타입으로 반환하고 있는 것 같네요.

그렇다면 잠깐 상상을 해봅시다.
List 인터페이스의 구현 클래스로는 ArrayList, LinkedList, Vector 등이 있는데,
`asList()` 메서드의 반환 값은 런타임에 상황에 따라 동적으로 결정된다 라고 상상을 해봐요.

만약 인터페이스 타입으로 반환하지 않는다면 어떤 일이 벌어질까요?

```java
// 인터페이스 타입으로 반환하는 경우
public static <T> List<T> asList(T... a) {
    return new ArrayList<>(a);
}
```

```java
// 인터페이스 타입으로 반환하지 않는 경우
public static <T> ArrayList<T> asList(T... a) {
    return new ArrayList<>(a);
}

public static <T> LinkedList<T> asList(T... a) {
    return new LinkedList<>(a);
}

public static <T> Vector<T> asList(T... a) {
    return new Vector<>(a);
}

...
```

동일한 기능을 하는 메서드임에도, 추가적인 메서드를 구현해야 하는 모습을 확인할 수 있습니다.
이 글의 첫 문장에서 "구현해야 할 메서드의 개수가 적어진다." 라고 언급했는데, 잘 지켜진 것 같네요.

다만, 제가 위에서 든 예시는 유효하지 않은 코드입니다.
장점 네 번째에 보면, EnumSet 클래스 예시를 들고 있습니다.

```java
// EnumSet.java
public static <E extends Enum<E>> EnumSet<E> noneOf(Class<E> elementType) {
    Enum<?>[] universe = getUniverse(elementType);
    if (universe == null)
        throw new ClassCastException(elementType + " not an enum");

    if (universe.length <= 64)
        return new RegularEnumSet<>(elementType, universe);
    else
        return new JumboEnumSet<>(elementType, universe);
}
```
EnumSet에서 기본적으로 제공하는 정적 팩터리 메서드는 원소의 개수가 64개 이하냐, 초과냐에 따라 서로 다른 구현 클래스를 반환하고 있습니다. EnumSet 역시 마찬가지로 정적 팩터리 메서드의 반환 타입이 인터페이스이기 때문에 하나의 noneOf 메서드로 이런 일이 가능하게 된 것입니다.

도움이 되셨나요?

**Comment by choigy1001** [comment]
예시랑 설명 감사합니다~ 읽어보니 장점에 대한 의미가 무엇인지 잘 이해할 수 있었네요!
