### ISSUE TITLE
[아이템 2] 빌더 패턴을 계층적으로 사용하는 부분의 코드를 모르겠어요.

### ISSUE THREAD

**Issue by choigy1001** [Reading-Effective-Java/community#3]
페이지 20~21에 관한 내용입니다.
`Nypizza` 코드를 보면 대응하는 메소드들을 알겠는데,
`Calzone` 코드를 보면 `Builder()`에 관한 내용을 제 머리로는 찾을 수 가 없네요..
이 부분에서 어떻게 `Builder()` 가 나오게 되었는지 궁금합니다! 
```java
NyPizza pizza = new Nypizza.Builder(SMALL)
		.addTopping(SAUSAGE)
		.addTopping(ONION)
		.build();
CalZone calzone = new Calzone.Builder()
		.addTopping(HAM)
		.sauceInside()
		.build(); 
```

**Comment by choigy1001** [comment]
공부하다 보니 생각이 났는데  단순히 상속받은 클래스가 상위 클래스로 부터 생성자를 받아 호출하게 되나요?...

**Comment by jhparkland** [comment]
교수님께서 하위클래스의 생성자에 super()라는게(다로 작성하지 않을경우) 자동으로 실행되어서 부모생성자의 기본생성자가 실행된다고 배웠는데 이게 맞는 답변인지 모르겠습니다..

**Comment by JinseongHwang** [comment]
답이 늦었네요... ㅎㅎ 조금 바빴네요. 양해 부탁드립니다.

저는 질문을 이렇게 이해했습니다.
**NyPizza에는 Builder 생성자가 있고, Calzone에는 생성자가 없는데 어떻게 생성자를 호출할 수 있냐?**

우선, **Java의 모든 클래스는 하나 이상의 생성자를 가지고 있어야 한다**라는 원칙이 있습니다.
만약 프로그래머가 생성자를 하나도 만들지 않았다면 자바 컴파일러가 자동으로 기본 생성자를 만들어줍니다.
위 상황에서는 아래와 같이 말이죠.
```java
// Default constructor
Builder() {}
```

그래서 Calzone 클래스에서는 기본 생성자를 사용한 것이고, NyPizza 클래스에서는 프로그래머가 생성한 생성자를 사용한 것입니다.
다르게 표현하면, NyPizza 클래스에서는 기본 생성자를 프로그래머가 재정의 했다고도 할 수 있겠네요.

명확하게 답변하기 어려워서, 간단하게 코드를 작성해봤어요.
[여기](https://github.com/Reading-Effective-Java/community/tree/master/src/main/java/chapter02/item02/issue03) 확인해주세요.
실행해보시고, 잘 이해가지 않는 부분이 있다면 comment 남겨주세요.

**Comment by choigy1001** [comment]
> 교수님께서 하위클래스의 생성자에 super()라는게(다로 작성하지 않을경우) 자동으로 실행되어서 부모생성자의 기본생성자가 실행된다고 배웠는데 이게 맞는 답변인지 모르겠습니다..

코드를 다시 보니  Calzone이 빌더 클래스를 상속받다보니  기본 생성자인 Builder를 쓸 수 있는거 같네요..

**Comment by choigy1001** [comment]
@JinseongHwang 

제가 궁금했던점이랑 맞는거 같아요.
코드 실행해보니 궁금했던 점, 답변 내용 확실하게 이해 할 수 있었습니다!
