### ISSUE TITLE
[아이템 8] finalizer, cleaner사용을 피하라 에서 영구 락 해제에 대해 이해가 안됩니다.

### ISSUE THREAD

**Issue by jhparkland** [Reading-Effective-Java/community#4]
책의 41p 3번째문단에 데이터베이스 같은 공유 자원의 영구 락 해제를 finalizer, cleaner 맡겨 놓으면 분산 시스템 전체가 서서히 멈출 것이다.  이 문장에서 lock의 개념을 몰라서 
https://brunch.co.kr/@kd4/156 이 사이트에서 lock에 대한 내용을 알아보았는데 
책의 문장에 있는 lock이 해제된다는 말이. ```synchronized```이 동작하면서 특정 thread가 동작할 때  다른 thread가 접근하지 못하게 했다가 다른 thread의 접근을 허용하게 할 시점을 이야기하나요?

예를 들면 thread1과 thread2가 있을 경우 thread1이 실행될 동안 thread2의 접근을 막고 있다가 thread2가 실행이 되면 그때가 thread2의 lock이 해제되었다고 표현하나요?

아니면 unlock() 이라는 것을 의미하나요? 

분산 시스템이 서서히 멈출 것이다. 의  의미는
gc가 ```finalizer```와 ```cleaner```를 호출하는데 하지만 그게 언제인지도 모르기 때문에 OOM 이나 기타 오류,장애를 발생해서 서서히 멈춘다는 말을 쓰는 건가요?

**Comment by kkt219a** [comment]
"데이터베이스 같은 공유 자원의 영구 락 해제를 finalizer, cleaner 맡겨 놓으면 분산 시스템 전체가 서서히 멈출 것이다."
라는 게 저는 자바에서 Lock 개념이 아닌 데이터베이스에서 락 개념으로 이해했어요. 데이터베이스에서 공유자원에 락을 거는 경우가 있는데,
간단한 예로 영화표 예약을 생각하시면 될거같아요. 아래 예시에 대한 솔루션은 다양하게 존재하지만 현상을 설명하기 위해 내용을 국한합니다.

두 사람이 동시에 같은 자리를 모바일로 확인했고, 그 중 한사람이 먼저 그 자리를 선점하고 결제에 들어간다고 가정할게요.
그 사람이 결제를 할지, 안 할지 몰라요. 모르기 때문에 그 자리는 이미 팔렸다고 생각할 수도 없고 그렇다고 두번째 사람을 결제가 가능하게
올려보내준다면? 첫번째 사람 입장에선 결제가 되는 줄 알고 들어왔는데 결제에 실패하거나, 두 명이 거의 동시에 결제한다면 1개의 자리에 
두 사람이 결제를 한 게 될 수 있죠. 

멀티 쓰레드 환경에서 더욱 취약할 것이고 결제가 진행되기 직전, 결제를 한 후 매번 데이터베이스에
접근한다는 것은 낭비입니다. 특정한 사람이 그 자리의 상태를 업데이트(구매된 것으로)할 것으로 예상되면 데이터베이스에서
처리가 되기 전까지 Lock을 걸 수 있어요. 두번째 사람은 첫번째 사람이 자리를 선택해서 구매과정을 거치고 있다면 못들어가게
막는거죠. 실제 팔리지 않았더라도.

그러면 첫번째 사람이 구매를 하지 못했을때 데이터베이스에 lock을 따로 해줘야하는데,
구매를 하지 못한이유가 단순변심일 수도 있고 시스템 익셉션일수도 있기 때문에 시스템 익셉션일 경우 예외처리를 하면서
데이터베이스 자원의 락해제를 해줘야할텐데, 그걸 finalizer나 cleaner에 맡길 경우, 본문에 나와있듯 언제인지도 모르고
그게 실제로 발생할지도 모른다는 것이죠?

그렇게 데이터베이스 공유자원에 걸린 영구락이 시스템 전반적으로 나타난다면 많은 자원들에 접근이 잠길 것이고,
사이드 이펙트로 분산 시스템 전체가 서서히 멈춘다는 것으로 이해했어요. 저파트에 정확한 설명이 없어서 이게 확실한진 모르겠으나
데이터베이스 공유자원에 대한 설명을 넣었다면 이게 맞을 것 같아요

**Comment by jhparkland** [comment]
감사합니다 이해 완료했습니다 ^^
