### ISSUE TITLE
[아이템 8] 코드 부분 설명에 포인터, clean 메소드, run 메소드

### ISSUE THREAD

**Issue by choigy1001** [Reading-Effective-Java/community#5]
44페이지 마지막 문단부터 시작입니다.
첫 번째 질문으로는 포인터 입니다. 
`numJunkPiles` 필드가 네이티브 피어를 가리키는 포인터를 담은 
`final long` 변수여야 한다고 했는데 자바에서 포인터는 없고 참조값을 대신 사용하여 담는다는 얘기인가요? 

두 번째는 `run` 메소드가 Room의  `close` 메소드를 호출할때 호출된다고 했습니다. 제 생각은 `clean`이 구현이 아직 안되어 있어 `run`을 사용할 수 없는 거 같은데 다른 분들의 생각은 어떠하신가요?

세 번째로 `run` 메소드는 `cleaner`의 안전망으로 쓰여진 메소드인가요? cleaner에 대해 추가 설명이 필요합니다..

**Comment by jhparkland** [comment]
우선 2번째, 3번째 질문부터 답변을 드리자면(1번은 조금 더 알아보겠습니다.)
~~~
import java.lang.ref.Cleaner;

public class Room implements AutoCloseable {

	private static final Cleaner cleaner = Cleaner.create();

	private static class State implements Runnable {
		int numJunk;

		State(int numJunk) {
			this.numJunk = numJunk;
		}

		// close 메서드나 cleaner가 호출한다
		@Override
		public void run() {  
			System.out.println("방 청소");
			numJunk = 0;
		}
	}

	private final State state; // 방의 상태 cleanable과 공유함.
        //cleanable.clean()에 의해 run()이 실행되어서 공유함 이라는 표현을 쓰는 것 같습니다.

	private final Cleaner.Cleanable cleanable; // 이거 가지고 clean함.

	public Room(int numJunk) {
		this.state = new State(numJunk);
		this.cleanable = cleaner.register(this, state);
		// 이때 cleanable 객체가 얻어진다.
	}

	@Override
	public void close() {
		cleanable.clean(); //clean

	}

	public static void main(String[] args) {
		try(Room myRoom = new Room(7)){  //AutoCloseable 때문에 close가 자동 실행됨.
			System.out.println("안녕~");
		}
	}
}
~~~
위 코드로 디버깅을 해보았는데요

우선 [아이템 9]에서 ```try - with -resources```는 ```AutoCloseable```과 같이 써야 한다고 이해했습니다 이유는 ```AutoCloseable``` 가 ```close```를 자동으로 실행시키는데 지금 코드에서는 ```close```를 Override하였으므로 Override한 코드가 실행될 것 입니다.

그리고 ```cleanable```은 cleaner.register(this(Room),State)에 의해서 값을 가지는데 이 과정에서 Cleaner.class의 
~~~
    public Cleanable register(Object obj, Runnable action) {
        Objects.requireNonNull(obj, "obj");
        Objects.requireNonNull(action, "action");
        return new CleanerImpl.PhantomCleanableRef(obj, this, action);
    }
~~~ 
부분을 거쳐서 값을 얻어옵니다.

그리고 이제 main의 ```try - with -resources```에 의해서 아까 ```close```가 자동으로 실행된다고 했으니.
~~~
	public void close() {
		cleanable.clean(); //clean

	}
~~~
이 메서드가 동작을 할텐데....

이 부분은 저의 추측이지만....
```clean()```이라는 메서드는  ```cleanable```가 가지는 주소(?) ( CleanerImpl$PhantomCleanableRef ) 에 의해
PhantomCleanable.class 로 이동하는데 이곳에  clean이 구현 되어있습니다.
~~~

    @Override
    public final void clean() {
        if (remove()) {
            super.clear();
            performCleanup();
        }
    }
~~~
이 메서드를 통해 ```remove()```라는 메서드가 호출되고 (remove메서드의 코드도 이해가 안되었습니다...)

```super.clear()```에 의해
Reference.class에 있는 
~~~
    public void clear() {
        this.referent = null;
    }
~~~ 
메서드가 호출이 됩니다.

그리고 ```performCleanup()``` 에 의해

cleanerlmpl.class에 있는 
~~~
        @Override
        protected void performCleanup() {
            action.run();
        }
~~~
메서드가 호출이 되고

비로소 예제 코드의 run 이 실행됩니다.

그래서 cleaner는 run의 안전망이라고 생각합니다.
Cleanable의 clean을 호출하면 이 메서드(clean)에서 run을 호출 할 것이고
가비지 컬렉터가 Room객체를 회수할 때 까지  클라이언트가 close를 호출하지 않는다면 State의 run메서드의 호출해줘서 
run()이라는 메서드가 실행이 되기 때문에 안전망이라고 하지 않을까 싶습니다...

제가 어떻게든 이해해서 설명을 해보려고 했지만.. 최대한 이해한 것이 이것밖에 되지 않아 진짜 너무 죄송합니다.

도움이 되었으면 좋겠습니다 ㅠㅠ

**Comment by JinseongHwang** [comment]
질문 1에 대한 제 생각을 말씀드릴게요.   

"왜 reference 라는 단어를 두고 포인터라고 작성했을까?"라는 의문을 가지고 생각해봤습니다.
_**아이템 8 finalizer와 cleaner 사용을 피하라**_

아이템명에서도 cleaner 사용을 피하라고 하는데, 왜 cleaner를 사용하는 예제를 보여줬을까요?

p.43에서 말하기를, 네이티브 피어 객체를 사용한다면 cleaner를 사용해도 적절하다고 합니다.
예제를 보여줬지만, 지면의 가독성을 고려해서 네이티브 피어 예제를 가져오기 힘들었을 것으로 추측됩니다.
그래서 네이티브 피어 객체를 int 변수 멤버로 대신한 것 같네요.

또한 네이티브 객체는 JVM에서 관리하는 객체가 아니기 때문에, **reference**라는 표현보다
OS 친화적인 C/C++에서 사용하는 표현을 빌려 **포인터**라고 표현한 것이 아닌가 라는 생각이 듭니다.

타입이 `final long`이라고 명시한 것에 대해서는 의문점이 풀리지 않았네요.
네이티브 객체 또한 Java application에서 사용하기 위해서는 객체의 주소를 알고 있어야 합니다.
JVM의 주소 체계를 따라가는 것이 아닌, OS의 주소 체계를 따라가는 것입니다.
최근 시점에서 대부분의 컴퓨터가 64bit 시스템이기 때문에 long 자료형을 사용했을 것이라 추측됩니다.
네이티브 객체의 주소를 계산하기 위해 java.lang.System의 `identityHashCode()` 네이티브 메서드를 사용할 것 같네요.
하지만 `identityHashCode()` 메서드에서는 int 를 반환하고 있네요... 후

온갖 추측만이 가득한 결론이네요 ㅠㅠ
다른 생각을 가지고 계신다면 공유해주시면 감사하겠습니다 😄

**Comment by choigy1001** [comment]
@JinseongHwang  설명 잘 읽었습니다. 저도 `final long`이라고 표현한 이유가
객체의 주소를 알기 위해 그렇게 선언한다고 이해했는데 네이티프 객체 주소를 위해서 `identityHashCode()`에서 int를 반환한다고 하니 또 얘기가 달라지겠네요. 추가로 이에 대해서 저도 찾아 보겠습니다.

**Comment by JinseongHwang** [comment]
@choigy1001 음 아니면, 사실상 int 타입으로도 충분하지만 하위 호환성을 위해 long으로 작성했을 것 같기도 하네요 ㅋㅋㅋ

**Comment by choigy1001** [comment]
@pwjdgus  엄청 자세하게 써주셔서 감사합니다! 쭉 읽어봤는데  
`PhantomCleanable` 메소드를 보고 Cleanable할 수 있는 참조값들을 리스트로 받아와 삽입해서  `clean` 메소드를 호출할 때 `remove`를 실행 할 수 있는 거 같네요! 전체적으로 흐름을 파악하는데 더할 나위 없었습니다.  
다만 이제 `new Room(99)`가 왜 방 청소가 출력이 안되는지 더 알아봐야겠네요..

**Comment by jhparkland** [comment]
우선 추측을 2가지 해봤습니다.
 
첫 번째는

아이템 8의 내용이 ```finalizer``` 랑``` cleaner```는 수행 여부를 보장 하지 못 합니다. 
그래서 제대로 닫힘을 보장하는 수단으로 아이템 9의 내용인 ```try-finally```와 ```try - with - resources```가 있었는데

예제코드는``` AutoCleanable``` 을 이용하니 ```try - with - resources```을 이용하여 자원이 제대로 닫힘을 보장했다면

new Room은 자원이 제대로 닫힘을 보장하는 수단이 없습니다. 
심지어 ```System.gc()``` ( ```finalizer``` 랑``` cleaner```가 실행될 가능성을 높여 줄 수 있기도 함) 조차 쓰이지 않았습니다.

때문에 자원이 잘 닫히지 않아서 방 청소라는 문장이 결코 수행하지 않는다고 생각합니다.
( 앞의 코드는 ```close()```를 통해서 ```run()```이 동작했기 때문에 방 청소 동작)

그리고 p45의 3번째 줄부터

gc가 Room 을 회수할 때 까지 클라이언트가 close를 호출하지 않는다면(```new Room(99)``` 같은 상황 이라 생각합니다)
cleaner가 State 의 run()을 호출해줄 것이다.

때문에 책에서도 Systme.gc()를 실행하니 방 청소가 동작했다는 결론이 나온 듯 합니다.

2번째는 

new Room(99); 라는걸 보고 저렇게도 가능한가.,.? 라는 의문이 들어서

어디 변수에 담지 않는 이상 공간만 만드는 거라고 추측을 하고

무조건 힙 영역에 생성되지 않을거라 생각했습니다.(```Class Area(=Method Area)```에 생성된다고 생각합니다)

그러면 자원 회수도 불가능하겠죠 gc를 쓴다해도 힙 영역에 있지 않다면 무용지물이니까 p46의 마지막 문장에
"여러분의 컴퓨터에서도 그러리라 보장은 없다"의 의미가 되지 않을까 싶습니다.


우선은 이렇게 생각을 해봤는데요 저도 조금 더 알아보겠습니다....

**Comment by jhparkland** [comment]
추가로 ```new Room(99)```에서 ```@SuppressWarnings("resource")```경고가 
나와서 찾아보니

resources : 닫기 가능 유형의 자원 사용에 관련된 경고 억제 라는 의미래요
