### ISSUE TITLE
[아이템 8] close()의 호출을 누가 하는지 궁금합니다.

### ISSUE THREAD

**Issue by JinseongHwang** [Reading-Effective-Java/community#7]
아래는 책에 나오는 Cleaner 예제입니다.

```java
public class Room implements AutoCloseable {

    private static final Cleaner CLEANER = Cleaner.create();

    private final State state;

    private final Cleaner.Cleanable cleanable;

    public Room(int numJunkPiles) {
        state = new State(numJunkPiles);
        cleanable = CLEANER.register(this, state);
    }

    @Override
    public void close() throws RuntimeException {
        System.out.println("close() 메서드 호출");
        cleanable.clean();
    }
    
    // 청소가 필요한 자원. 절대 Room을 참조해서는 안된다.
    private static class State implements Runnable {
        int numJunkPiles; // 방(Room) 안의 쓰레기 수 = 수거할 자원

        State(int numJunkPiles) {
            this.numJunkPiles = numJunkPiles;
        }

        // close 메서드나 cleaner가 호출된다.
        @Override
        public void run() {
            numJunkPiles = 0;
            System.out.println("청소 완료");
        }
    }
}
```

## 질문

AutoClosable 인터페이스의 오버라이딩된 `close()` 메서드는 어디에서 호출이 되나요?

**Comment by JinseongHwang** [comment]
#5 를 보고 일부 해결된 질문이 있어 내용을 변경했습니다.

**Comment by jhparkland** [comment]
답변의 흐름상 질문 2부터 이야기 하겠습니다!

# **질문2.**

```try-with-resuroces```는 우선 ```AutoCloseable```반드시 같이 쓰입니다.
~~~
try(resources){
........
}
~~~ 
형식으로 사용됩니다

```try(){} ```가 끝나고 나면 ```JVM```이 ```close()```를 자동으로 호출 시켜주는데
```AutoCloseable```라는 인터페이스에 ```close()```는 구현이 되어있지 않기에

```AutoCloseable```반드시 같이 쓰여야 한다고 생각합니다.

자신의 클래스에 ```AutoCloseable```을 ```implements```를 하여``` close()```를 재정의 합니다.

그리하여 ```try() {}```를 통해 JVM이 자동으로 ```close()```를 호출할 때 재정의한 ```close() ```메서드가 호출이 됩니다!

# **질문 1**

```private static final Cleaner cleaner = Cleaner.create(); ```를 통해 새로운 클리너를 만듭니다.

```private final Cleaner.Cleanable cleanable;```는 ```register( obj(Room), Runnable action(State) )```을 쓰기위해 사용되는
```Modifier and Type```입니다. 

```register()```는 개체를 등록하고 개체가 팬텀에 연결할 수 있게 되면 실행할 __정리__ 작업을 등록합니다.
그 메서드의 리턴값을 ```cleanable```에 저장합니다.

그리고 ```try-with-resuroces```에 의하여 ```JVM```에서 ```close()```자동 호출하는데 이 메서드는 ```Room```이라는 클래스에 재정의 되어있어서
재정의된 ```close()```가 동작할겁니다. 

재정의된 ```close()```메소드가 호출되면 내부의 ```cleanable.clean(); ```가 호출될텐데

```cleanable```안에는 ```register```메서드에 의해 리턴된 정보가 들어있습니다. 그 정보가 어떠한 팬텀을 의미하는 거라고 생각합니다.
왜냐면 ```register()```에  ```return new CleanerImpl.PhantomCleanableRef(obj, this, action);```라고 적혀있고. 이 부분이 개체를 팬텀에 연결하는 부분이라 생각됩니다.

따라서 그 팬텀(?)클래스에 있는 재정의된 ```clean()```이 호출되어 자원 회수가 진행됩니다!

https://docs.oracle.com/javase/9/docs/api/java/lang/ref/Cleaner.html
https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html
https://velog.io/@aidenshin/try-with-resource
위 사이트를 참고 하였습니다.

**Comment by jhparkland** [comment]
엇...제가 글을 좀 정리한다고 늦었는데 글이 수정이 되었네요

**Comment by JinseongHwang** [comment]
@pwjdgus 우선 답변 고마워요.
근데 JVM이 close()를 호출한다고 했는데, JVM 내부에서 어떤 유틸리티 클래스 형태로 제공될까요?
분명 어디선가 close() 를 호출하는 코드가 있을텐데 안보이네요...

```java
class JvmClose {
   
    void doSomething() {
        Room room = new Room(10);
        // TODO
        room.close();
    }
}
```

**Comment by jhparkland** [comment]
우선 **try-with-resources에서 자동으로 close가 호출되는 것은 AutoCloseable을 구현한 객체에만 해당이 됩니다.** 

```Scanner```도 ```close```를 쓰니까 혹시 내부에 어떻게 되어있을지 한번 보았습니다.

```Scanner```에서는 ```Closeable```이라는 인터페이스를 사용하는데 

```Closeable```은 ```java.io```에 있었습니다.

```Closeable```의  내용을 보면 
~~~
public interface Closeable extends AutoCloseable {

    /**
     * Closes this stream and releases any system resources associated
     * with it. If the stream is already closed then invoking this
     * method has no effect.
     *
     * <p> As noted in {@link AutoCloseable#close()}, cases where the
     * close may fail require careful attention. It is strongly advised
     * to relinquish the underlying resources and to internally
     * <em>mark</em> the {@code Closeable} as closed, prior to throwing
     * the {@code IOException}.
     *
     * @throws IOException if an I/O error occurs
     */
    public void close() throws IOException;
}
~~~ 

close()가 보이는데 ```AutoCloseable```을 상속받고 있습니다.

그리고 ```AutoCloseable```에 주석처리된 부분을 읽으면

 This method is invoked automatically on objects managed by the
  {@code try}-with-resources statement. 라고있는데

 번역을 하니 이 메서드는 리소스 ```try-with-resource``` 문으로 관리되는 개체에서 자동으로 호출됩니다.
 라고 쓰여있더군요 

만약 ```Scanner```를 사용할때 명식적으로``` close```를 사용하지 않으면 자원 누수가 일어나겠죠
그래서 보통 ```Scanner.close```를 하는데 이렇게 명시하기 싫고 자원 누수를 막고 싶을 때
```try-with-resources```를 사용한다고 합니다.


정리하자면
```try-with-resources```를 사용할 때 ```close```가 자동으로 호출된 다는 것은
```AutoCloseable```을 구현한 객체에 해당하고 (java.lang.AutoCloseable) => **lang패키지는 import없이 사용이 가능하다고 합니다.**
( 그래서 JVM이 자동으로 호출 시킨다는 말은```AutoCloseable```을 사용하는 객체에 있는 재정의된 ```close```가 아닌가는 생각이 드네요)

close함수를 명시 할 수 있는 객체들 ex``` BufferedInputStream ``` , ```Scanner```는
모두 Closeable을 통해 AutoCloseable을 사용하고 있습니다.

따라서 개발자가 ```close```함수를 명시하기 싫을 때 혹은 보장 받지 못할 때
```try-with-resources```를 통하여 ```close```를 실행 시키는 것 을 볼 수 있습니다.


https://codechacha.com/ko/java-try-with-resources/ 
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
에서 참고 하였습니다.

혹시 도움이 조금 되실까요? 의도하신 답변이 아니라면 다시 알아보겠습니다.

**Comment by JinseongHwang** [comment]
정말 열심히 작성해 주셨는데, 원하는 답이 없네요..
이쯤에서 그만할까 생각이 들다가도, 궁금해서 계속 찾아봤어요.
해답은 아니고 꽤 만족스러운 단서를 찾았는데 한 번 들어봐주시겠어요?

-----

<br>

다시 처음 질문으로 되돌아가볼게요.
Room 클래스의 close() 메서드는 누가 호출할까요?

책에 나와있는 Room의 클라이언트인 Adult 클래스를 살펴봅시다.

아래는 Adult.java 파일입니다.
```java
public class Adult {
    public static void main(String[] args) {
        try (var myRoom = new Room(7)) {
            System.out.println("안녕~");
        }
    }
}
```

이 java 파일을 decompile된 class 파일을 찾아볼 수 있었습니다.
아래는 Adult.class 파일입니다.
```java
public class Adult {
    public Adult() {
    }

    public static void main(String[] args) {
        Room myRoom = new Room(7);

        try {
            System.out.println("안녕~");
        } catch (Throwable var5) {
            try {
                myRoom.close();
            } catch (Throwable var4) {
                var5.addSuppressed(var4);
            }

            throw var5;
        }

        myRoom.close();
    }
}
```
마지막에 보시면 `myRoom.close()` 메서드를 호출하는 것을 확인할 수 있었습니다.
tip) 이렇게 코드를 숨겨서 간략하게 만들어주는 것을 [Syntactic sugar](https://en.wikipedia.org/wiki/Syntactic_sugar)라고 하더라고요.

따라서 `close()` 메서드는 JVM이 실행은 해주겠지만, 컴파일러가 작성해 주는 코드입니다.
즉, close() 메서드를 호출하는 것은 JVM과는 관련이 없습니다.
컴파일러가 try-with-resources 를 보면 그냥 알아서 `close()` 메서드를 추가해 주는 것 같네요.

마치 Javascript는 class 기능이 없지만, 편의상 class를 만들어둔 것과 비슷한 원리일까요?

-----

<br>

저는 JVM이 무슨 마법을 부려 close() 메서드를 호출해 주는 줄 알았는데,
그게 아니라 그냥 개발 편의성을 위해 숨겨둔 것이었고,
컴파일러가 다시 꺼내주는 역할을 수행하는 것으로 정리할 수 있겠네요.

질문이 모호해서 고생 많이 하셨어요 ㅠㅠㅠ 감사합니다

**Comment by jhparkland** [comment]
아직 제가 많이 부족하네요 ㅎㅎ....  열심히 찾아보고 물어보고 하겠습니다
