### ISSUE TITLE
[아이템 11] 좋은 hashCode 구현

### ISSUE THREAD

**Issue by kkt219a** [Reading-Effective-Java/community#8]
p69에 2.a.ii에 따르면 필드의 equals를 재귀적으로 호출해 비교하면 hashCode를 재귀적으로 호출하는 것 까진 이해했는데
필드의 표준형을 만들어 표준형의 hashCode를 호출하면 69p 제일 아래에 나오는 equals 비교에 사용되지 않은 필드는 
반드시 제외하라고 되어있는데 위에서 표준형을 만들 경우 equals에 사용하지 않은 표준형 필드를 사용하게 되는 것인데,
63p 4문단에 나온 equals 표준형으로을 선행하고 표준형 hashCode를 재정의하란게 함축된거 맞을까요?

다들 어떻게 생각하세요?

**Comment by meanjoo** [comment]
표준형을 만들면 equals 비교에 사용되는 필드가 표준형이 되어서 표준형(핵심 필드)의 hashCode를 재정의하는 거 아닐까요?

기존의 필드를 equals 비교에 사용하면 복잡하다고 판단될 때 비교를 덜 복잡하게 하려고 필드의 표준형을 만드는 것이기 때문에, 필드의 표준형을 만들게 된다면 equals 비교에서 표준형을 사용하니까 equals 비교에서 사용되지 않은 필드가 표준형이 아니라 기존의 필드라고 이해했어요.


```
//equals 메서드가 대소문자를 구별하지 않는 클래스
public class CaseInsensitiveString {
	
	private final String s;
	private final String sForEquals; //equals 단순화를 위한 필드 s의 표준형
	
	public CaseInsensitiveString(String s) {
		if (s == null) {
			throw new IllegalArgumentException();
		}
		this.s = s;
		this.sForEquals = s.toUpperCase();
	}
	
	@Override
	public boolean equals(Object o) {
		return o instanceof CaseInsensitiveString &&
				((CaseInsensitiveString) o).sForEquals.equals(this.sForEquals);
	}
	
	@Override
	public int hashCode() {
		return sForEquals.hashCode();
	}
}
```
(https://stackoverflow.com/a/24428722/11285469 에서 가져왔습니다.)
재정의한 equals에서 표준형을 사용하여 비교하기 때문에 hashCode를 재정의할 때도 표준형의 hashCode를 재정의해야 한다고 생각해요.

**Comment by jhparkland** [comment]
@kkt219a 답변을 드려야 하는데 제가 2.a.ii를 이해를 못 하고 있어서 
필드의 equals를 재귀적으로 호출해 비교하면 hashCode를 재귀적으로 호출하는 것 에 대한 설명을 혹시 가능하실까요?

**Comment by choigy1001** [comment]
@pwjdgus 
재귀적으로 호출한다는 의미는 이제 팩토리얼 구현하면서 대충 어떤 느낌인지 아실거에요
2.a.ii에 참조 타입 필드면서 재귀적으로 호출하는 것에 대해
만약 `String s="test" ` 로 s의 글자수를 알기 위해
test-> est -> st -> t 이런식으로 재귀호출한다하면 4번의 재귀를 통해 얻게 될건데 
이때 해쉬코드 또한 
`result = c * result + stringAddress == null ? 0 : stringAddress.hashCode();`
이런식으로 null일 경우엔 0 아니면 hashCode를 다시 호출하는게 아닌가 싶네요
