### ISSUE TITLE
[아이템 12] 테스트 실패 메시지

### ISSUE THREAD

**Issue by meanjoo** [Reading-Effective-Java/community#9]
74p에서 toString에 주요 정보가 담기지 않았을 때 테스트 실패 메시지의 예로 
`Assertion failure: expected {abc, 123}, but was {abc, 123}` 를 들고 있는데 왜 단언 실패인가요?

예상값이 {abc, 123}이고 실젯값이 {abc, 123}이면 같은 거라서 성공이라고 생각했는데 이게 아닌가요..?

**Comment by jhparkland** [comment]
맞는지 모르겠지만 제 생각에는 toString이 자동으로 호출되는 상황이 있습니다

- println, printf할 때
- 문자열연결연산자(+)로 연결할 때
- assert구문에 넘길 때
- 디버거가 객체를 출력할 때

그리고 책을  보니 **테스트 실패 메시지의 예** 라는 걸로 봐서 
assert 관련된 작업을 한 것 같고
https://jongmin92.github.io/2020/03/31/Java/use-assertthat/<<참고 했습니다.

toString에 주요 정보가 담기지 않았을 때라는 가정이 있을 경우  {첫 번째, 두 번째}의 관계(?)가 맞지 않다는 이야기 아닐까요??

**Comment by meanjoo** [comment]
답변을 보고 다시 생각해보니 제가 살짝 당연한 내용을 질문한 것 같은 기분이 들긴 하지만.. 이런 말인 것 같습니다!
```
public class Apartment {
	private String name;
	private final int dong, ho;
	
	public Apartment(String name, int dong, int ho) {
		this.name = name;
		this.dong = dong;
		this.ho = ho;
	}
	
	@Override
	public String toString() {
		return String.format("%s, %d", name, dong);
	}
}
```
Apartment 객체는 이름, 동, 호 세 개의 주요 정보를 가지는데, 재정의된 toString은 이름과 동 정보만을 반환하고 있습니다. 
```
Apartment a1 = new Apartment("abc", 101, 1101);
Apartment a2 = new Apartment("abc", 101, 502);
```
a1, a2 객체를 만들고 Junit을 통해서 a1과 a2가 같은지 테스트해보면 실패하는데 이때
`Expected: is <abc, 101> but: was <abc, 101>` 라는 메시지가 출력되는 것을 확인했습니다.

주요 정보가 담기지 않았을 때 실패했다면 무엇 때문에 실패한지 메시지를 통해 알 수 없는 것이 문제인데,
만약 toString이 이름, 동, 호 모든 정보를 반환해주었다면 실패 메시지가 `Expected: is <abc, 101, 502> but: was <abc, 101, 1101>` 이렇게 출력돼서 이걸 보고 왜 실패한지 알 수 있어서 toString은 객체가 가진 주요 정보를 모두 반환하는 게 좋다고 말하는 거 같아요.

assert 관련해서 잘 모르고 있었는데 덕분에 어느 정도 알게 된 거 같아요. 감사합니다!

**Comment by jhparkland** [comment]
저도 질문 덕분에 그냥 대수롭게 넘긴 것을 다시 봤습니다 ! 감사합니다
